[2025-08-17T18:36:28.830+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-17T18:36:28.896+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dvc.train_fraud_detector_dvc manual__2025-08-17T18:35:45.412026+00:00 [queued]>
[2025-08-17T18:36:28.916+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dvc.train_fraud_detector_dvc manual__2025-08-17T18:35:45.412026+00:00 [queued]>
[2025-08-17T18:36:28.917+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-17T18:36:28.948+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_fraud_detector_dvc> on 2025-08-17 18:35:45.412026+00:00
[2025-08-17T18:36:28.962+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2259) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-17T18:36:28.966+0000] {standard_task_runner.py:63} INFO - Started process 2276 to run task
[2025-08-17T18:36:28.966+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dvc', 'train_fraud_detector_dvc', 'manual__2025-08-17T18:35:45.412026+00:00', '--job-id', '311', '--raw', '--subdir', 'DAGS_FOLDER/train_pipeline_dag.py', '--cfg-path', '/tmp/tmpq26czusf']
[2025-08-17T18:36:28.970+0000] {standard_task_runner.py:91} INFO - Job 311: Subtask train_fraud_detector_dvc
[2025-08-17T18:36:29.085+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline_dvc.train_fraud_detector_dvc manual__2025-08-17T18:35:45.412026+00:00 [running]> on host bea494a05fb4
[2025-08-17T18:36:29.290+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yas' AIRFLOW_CTX_DAG_ID='ml_pipeline_dvc' AIRFLOW_CTX_TASK_ID='train_fraud_detector_dvc' AIRFLOW_CTX_EXECUTION_DATE='2025-08-17T18:35:45.412026+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-17T18:35:45.412026+00:00'
[2025-08-17T18:36:29.294+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-17T18:36:29.324+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-17T18:36:29.326+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            cd /opt/***/ml_pipeline\n            dvc pull\n            dvc repro train_model\n            dvc push\n        ']
[2025-08-17T18:36:29.346+0000] {subprocess.py:86} INFO - Output:
[2025-08-17T18:36:33.865+0000] {subprocess.py:93} INFO - ERROR: failed to pull data from the cloud - Can't remove the following unsaved files without confirmation. Use `--force` to force.
[2025-08-17T18:36:33.866+0000] {subprocess.py:93} INFO - /opt/***/ml_pipeline/artifacts/models/fraud/metadata_model_v20250817_175136.json
[2025-08-17T18:36:37.272+0000] {subprocess.py:93} INFO - Stage 'ingest' didn't change, skipping
[2025-08-17T18:36:37.307+0000] {subprocess.py:93} INFO - Stage 'preprocess' didn't change, skipping
[2025-08-17T18:36:37.358+0000] {subprocess.py:93} INFO - Running stage 'train_model':
[2025-08-17T18:36:37.359+0000] {subprocess.py:93} INFO - > python models/train_fraud_detector_task.py
[2025-08-17T18:36:40.891+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-17 18:36:40,846", "levelname": "INFO", "name": "model_training", "trace_id": null, "span_id": null, "message": "MLflow run id: 3fcb0e656e9b4adc80b9b86a8ed399a2"}
[2025-08-17T18:36:40.964+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-17 18:36:40,964", "levelname": "INFO", "name": "model_training", "trace_id": null, "span_id": null, "message": "Loading preprocessor from artifacts/preprocess/fraud_pipeline_v20250817_175136.pkl to process raw data"}
[2025-08-17T18:36:40.996+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-17 18:36:40,995", "levelname": "INFO", "name": "model_training", "trace_id": null, "span_id": null, "message": "Preprocessing/transform applied to raw data."}
[2025-08-17T18:36:41.036+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-17 18:36:41,033", "levelname": "INFO", "name": "model_training", "trace_id": null, "span_id": null, "message": "Evaluation metrics: {'accuracy': 0.998, 'f1_score': 0.9655172413793104, 'precision': 1.0, 'recall': 0.9333333333333333, 'auc': 0.9999312714776633}"}
[2025-08-17T18:36:48.875+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-17 18:36:48,875", "levelname": "INFO", "name": "model_training", "trace_id": null, "span_id": null, "message": "Model pipeline logged to MLflow (artifact_path='model')"}
[2025-08-17T18:36:48.961+0000] {subprocess.py:93} INFO - üèÉ View run train_v20250817_175136 at: http://mlflow:5000/#/experiments/2/runs/3fcb0e656e9b4adc80b9b86a8ed399a2
[2025-08-17T18:36:48.962+0000] {subprocess.py:93} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/2
[2025-08-17T18:36:48.963+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-17T18:36:48.963+0000] {subprocess.py:93} INFO -   File "/opt/***/ml_pipeline/models/train_fraud_detector_task.py", line 227, in <module>
[2025-08-17T18:36:48.963+0000] {subprocess.py:93} INFO -     main()
[2025-08-17T18:36:48.964+0000] {subprocess.py:93} INFO -   File "/opt/***/ml_pipeline/models/train_fraud_detector_task.py", line 214, in main
[2025-08-17T18:36:48.964+0000] {subprocess.py:93} INFO -     model_version = client.search_model_versions(f"name={MODEL_NAME} and run_id={run_id}")[0]
[2025-08-17T18:36:48.965+0000] {subprocess.py:93} INFO -                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-17T18:36:48.965+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/tracking/client.py", line 4817, in search_model_versions
[2025-08-17T18:36:48.967+0000] {subprocess.py:93} INFO -     return self._get_registry_client().search_model_versions(
[2025-08-17T18:36:48.968+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-17T18:36:48.968+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/tracking/_model_registry/client.py", line 393, in search_model_versions
[2025-08-17T18:36:48.969+0000] {subprocess.py:93} INFO -     return self.store.search_model_versions(filter_string, max_results, order_by, page_token)
[2025-08-17T18:36:48.969+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-17T18:36:48.969+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/store/model_registry/rest_store.py", line 401, in search_model_versions
[2025-08-17T18:36:48.970+0000] {subprocess.py:93} INFO -     response_proto = self._call_endpoint(SearchModelVersions, req_body)
[2025-08-17T18:36:48.970+0000] {subprocess.py:93} INFO -                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-17T18:36:48.971+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/store/model_registry/base_rest_store.py", line 42, in _call_endpoint
[2025-08-17T18:36:48.971+0000] {subprocess.py:93} INFO -     return call_endpoint(
[2025-08-17T18:36:48.972+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^
[2025-08-17T18:36:48.972+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 553, in call_endpoint
[2025-08-17T18:36:48.972+0000] {subprocess.py:93} INFO -     response = verify_rest_response(response, endpoint)
[2025-08-17T18:36:48.973+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-17T18:36:48.973+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 308, in verify_rest_response
[2025-08-17T18:36:48.974+0000] {subprocess.py:93} INFO -     raise RestException(json.loads(response.text))
[2025-08-17T18:36:48.974+0000] {subprocess.py:93} INFO - mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Parameter value is either not quoted or unidentified quote types used for string value FraudDetectionModel. Use either single or double quotes.
[2025-08-17T18:36:49.477+0000] {subprocess.py:93} INFO - ERROR: failed to reproduce 'train_model': failed to run: python models/train_fraud_detector_task.py, exited with 1
[2025-08-17T18:36:53.648+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-08-17T18:36:54.012+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-17T18:36:54.013+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-17T18:36:54.051+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ml_pipeline_dvc, task_id=train_fraud_detector_dvc, run_id=manual__2025-08-17T18:35:45.412026+00:00, execution_date=20250817T183545, start_date=20250817T183628, end_date=20250817T183654
[2025-08-17T18:36:54.105+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-17T18:36:54.126+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-17T18:36:54.128+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
