[2025-08-12T23:13:09.548+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T23:13:09.616+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-12T23:13:07.277547+00:00 [queued]>
[2025-08-12T23:13:09.664+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-12T23:13:07.277547+00:00 [queued]>
[2025-08-12T23:13:09.666+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-12T23:13:09.842+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): preprocess_dvc> on 2025-08-12 23:13:07.277547+00:00
[2025-08-12T23:13:09.874+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dvc', 'preprocess_dvc', 'manual__2025-08-12T23:13:07.277547+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/train_pipeline_dag.py', '--cfg-path', '/tmp/tmpnbaw21_p']
[2025-08-12T23:13:09.881+0000] {standard_task_runner.py:91} INFO - Job 212: Subtask preprocess_dvc
[2025-08-12T23:13:09.918+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1376) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-12T23:13:09.942+0000] {standard_task_runner.py:63} INFO - Started process 1377 to run task
[2025-08-12T23:13:10.094+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline_dvc.preprocess_dvc manual__2025-08-12T23:13:07.277547+00:00 [running]> on host 276ab97d4dd8
[2025-08-12T23:13:10.339+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yas' AIRFLOW_CTX_DAG_ID='ml_pipeline_dvc' AIRFLOW_CTX_TASK_ID='preprocess_dvc' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T23:13:07.277547+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-12T23:13:07.277547+00:00'
[2025-08-12T23:13:10.340+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T23:13:10.360+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-12T23:13:10.361+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/ml_pipeline && dvc repro preprocess']
[2025-08-12T23:13:10.374+0000] {subprocess.py:86} INFO - Output:
[2025-08-12T23:13:12.186+0000] {subprocess.py:93} INFO - './dvc.yaml' validation failed: 3 errors.
[2025-08-12T23:13:12.189+0000] {subprocess.py:93} INFO - 
[2025-08-12T23:13:12.190+0000] {subprocess.py:93} INFO - expected a dictionary, in stages -> preprocess -> outs -> 0 -> path, line 9,
[2025-08-12T23:13:12.191+0000] {subprocess.py:93} INFO - column 9
[2025-08-12T23:13:12.197+0000] {subprocess.py:93} INFO -    8 │   outs:
[2025-08-12T23:13:12.198+0000] {subprocess.py:93} INFO -    9 │     - path: s3://mlflow-artifacts/preprocess/${version_tag}/pipeline.pkl
[2025-08-12T23:13:12.199+0000] {subprocess.py:93} INFO -   10 │   │   cache: false
[2025-08-12T23:13:12.200+0000] {subprocess.py:93} INFO - 
[2025-08-12T23:13:12.201+0000] {subprocess.py:93} INFO - expected a dictionary, in stages -> preprocess -> outs -> 0 -> cache, line 9,
[2025-08-12T23:13:12.201+0000] {subprocess.py:93} INFO - column 9
[2025-08-12T23:13:12.202+0000] {subprocess.py:93} INFO -    8 │   outs:
[2025-08-12T23:13:12.203+0000] {subprocess.py:93} INFO -    9 │     - path: s3://mlflow-artifacts/preprocess/${version_tag}/pipeline.pkl
[2025-08-12T23:13:12.204+0000] {subprocess.py:93} INFO -   10 │   │   cache: false
[2025-08-12T23:13:12.205+0000] {subprocess.py:93} INFO - 
[2025-08-12T23:13:12.205+0000] {subprocess.py:93} INFO - expected a dictionary, in stages -> preprocess -> outs -> 0 -> persist, line 9,
[2025-08-12T23:13:12.206+0000] {subprocess.py:93} INFO - column 9
[2025-08-12T23:13:12.207+0000] {subprocess.py:93} INFO -    8 │   outs:
[2025-08-12T23:13:12.207+0000] {subprocess.py:93} INFO -    9 │     - path: s3://mlflow-artifacts/preprocess/${version_tag}/pipeline.pkl
[2025-08-12T23:13:12.208+0000] {subprocess.py:93} INFO -   10 │   │   cache: false
[2025-08-12T23:13:12.454+0000] {subprocess.py:97} INFO - Command exited with return code 255
[2025-08-12T23:13:12.455+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T23:13:12.471+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 255.
[2025-08-12T23:13:12.477+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ml_pipeline_dvc, task_id=preprocess_dvc, run_id=manual__2025-08-12T23:13:07.277547+00:00, execution_date=20250812T231307, start_date=20250812T231309, end_date=20250812T231312
[2025-08-12T23:13:12.501+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 212 for task preprocess_dvc (Bash command failed. The command returned a non-zero exit code 255.; 1377)
[2025-08-12T23:13:12.533+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-12T23:13:12.568+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-12T23:13:12.573+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
