[2025-08-12T16:32:17.884+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T16:32:18.036+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dvc.setup_dvc_remote manual__2025-08-12T16:32:16.878361+00:00 [queued]>
[2025-08-12T16:32:18.078+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dvc.setup_dvc_remote manual__2025-08-12T16:32:16.878361+00:00 [queued]>
[2025-08-12T16:32:18.080+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-12T16:32:18.120+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): setup_dvc_remote> on 2025-08-12 16:32:16.878361+00:00
[2025-08-12T16:32:18.135+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=306) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-12T16:32:18.139+0000] {standard_task_runner.py:63} INFO - Started process 307 to run task
[2025-08-12T16:32:18.139+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dvc', 'setup_dvc_remote', 'manual__2025-08-12T16:32:16.878361+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/train_pipeline_dag.py', '--cfg-path', '/tmp/tmp7nx6dfq5']
[2025-08-12T16:32:18.142+0000] {standard_task_runner.py:91} INFO - Job 120: Subtask setup_dvc_remote
[2025-08-12T16:32:18.292+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline_dvc.setup_dvc_remote manual__2025-08-12T16:32:16.878361+00:00 [running]> on host 08abdf02b345
[2025-08-12T16:32:18.694+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yas' AIRFLOW_CTX_DAG_ID='ml_pipeline_dvc' AIRFLOW_CTX_TASK_ID='setup_dvc_remote' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T16:32:16.878361+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-12T16:32:16.878361+00:00'
[2025-08-12T16:32:18.698+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T16:32:18.745+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-12T16:32:18.751+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /opt/***/ml_pipeline\n        dvc remote remove minio\n        dvc remote add -f minio s3://mlflow-artifacts\n        dvc remote modify minio endpointurl http://minio:9000\n        dvc remote modify minio access_key_id minioadmin\n        dvc remote modify minio secret_access_key minioadmin\n        dvc remote modify minio use_ssl false\n        dvc remote default minio\n        ']
[2025-08-12T16:32:18.774+0000] {subprocess.py:86} INFO - Output:
[2025-08-12T16:32:33.014+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-12T16:32:33.017+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T16:32:33.059+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ml_pipeline_dvc, task_id=setup_dvc_remote, run_id=manual__2025-08-12T16:32:16.878361+00:00, execution_date=20250812T163216, start_date=20250812T163218, end_date=20250812T163233
[2025-08-12T16:32:33.113+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-12T16:32:33.157+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-12T16:32:33.159+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
