[2025-08-17T17:52:44.056+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-17T17:52:44.094+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_dvc.train_fraud_detector_dvc manual__2025-08-17T17:51:27.498563+00:00 [queued]>
[2025-08-17T17:52:44.107+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_dvc.train_fraud_detector_dvc manual__2025-08-17T17:51:27.498563+00:00 [queued]>
[2025-08-17T17:52:44.108+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-17T17:52:44.131+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): train_fraud_detector_dvc> on 2025-08-17 17:51:27.498563+00:00
[2025-08-17T17:52:44.139+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-17T17:52:44.141+0000] {standard_task_runner.py:63} INFO - Started process 1131 to run task
[2025-08-17T17:52:44.141+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_dvc', 'train_fraud_detector_dvc', 'manual__2025-08-17T17:51:27.498563+00:00', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/train_pipeline_dag.py', '--cfg-path', '/tmp/tmpow_qhec_']
[2025-08-17T17:52:44.144+0000] {standard_task_runner.py:91} INFO - Job 303: Subtask train_fraud_detector_dvc
[2025-08-17T17:52:44.214+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline_dvc.train_fraud_detector_dvc manual__2025-08-17T17:51:27.498563+00:00 [running]> on host bea494a05fb4
[2025-08-17T17:52:44.359+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yas' AIRFLOW_CTX_DAG_ID='ml_pipeline_dvc' AIRFLOW_CTX_TASK_ID='train_fraud_detector_dvc' AIRFLOW_CTX_EXECUTION_DATE='2025-08-17T17:51:27.498563+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-17T17:51:27.498563+00:00'
[2025-08-17T17:52:44.361+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-17T17:52:44.388+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-17T17:52:44.390+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            cd /opt/***/ml_pipeline\n            dvc pull\n            dvc repro train_model\n            dvc push\n        ']
[2025-08-17T17:52:44.405+0000] {subprocess.py:86} INFO - Output:
[2025-08-17T17:52:47.999+0000] {subprocess.py:93} INFO - ERROR: failed to pull data from the cloud - Can't remove the following unsaved files without confirmation. Use `--force` to force.
[2025-08-17T17:52:48.000+0000] {subprocess.py:93} INFO - /opt/***/ml_pipeline/artifacts/models/fraud/metadata_model_v20250815_164605.json
[2025-08-17T17:52:50.979+0000] {subprocess.py:93} INFO - Stage 'ingest' didn't change, skipping
[2025-08-17T17:52:51.011+0000] {subprocess.py:93} INFO - Stage 'preprocess' didn't change, skipping
[2025-08-17T17:52:51.062+0000] {subprocess.py:93} INFO - Running stage 'train_model':
[2025-08-17T17:52:51.063+0000] {subprocess.py:93} INFO - > python models/train_fraud_detector_task.py
[2025-08-17T17:52:55.361+0000] {subprocess.py:93} INFO - 2025/08/17 17:52:55 INFO mlflow.tracking.fluent: Experiment with name 'FraudDetectionModel' does not exist. Creating a new experiment.
[2025-08-17T17:52:55.816+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-17 17:52:55,621", "levelname": "INFO", "name": "model_training", "trace_id": null, "span_id": null, "message": "MLflow run id: 17deb02ded5a4a7eb1d045ec53da69d2"}
[2025-08-17T17:52:55.897+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-17 17:52:55,897", "levelname": "INFO", "name": "model_training", "trace_id": null, "span_id": null, "message": "Loading preprocessor from artifacts/preprocess/fraud_pipeline_v20250817_175136.pkl to process raw data"}
[2025-08-17T17:52:55.933+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-17 17:52:55,933", "levelname": "INFO", "name": "model_training", "trace_id": null, "span_id": null, "message": "Preprocessing/transform applied to raw data."}
[2025-08-17T17:52:56.008+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-17 17:52:56,004", "levelname": "INFO", "name": "model_training", "trace_id": null, "span_id": null, "message": "Evaluation metrics: {'accuracy': 0.998, 'f1_score': 0.9655172413793104, 'precision': 1.0, 'recall': 0.9333333333333333, 'auc': 0.9999312714776633}"}
[2025-08-17T17:53:06.682+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-17 17:53:06,682", "levelname": "INFO", "name": "model_training", "trace_id": null, "span_id": null, "message": "Model pipeline logged to MLflow (artifact_path='model')"}
[2025-08-17T17:53:06.689+0000] {subprocess.py:93} INFO - {"asctime": "2025-08-17 17:53:06,689", "levelname": "INFO", "name": "model_training", "trace_id": null, "span_id": null, "message": "Registering model from runs:/17deb02ded5a4a7eb1d045ec53da69d2/model as registered model name 'FraudDetectionModel'"}
[2025-08-17T17:53:07.040+0000] {subprocess.py:93} INFO - Successfully registered model 'FraudDetectionModel'.
[2025-08-17T17:53:07.523+0000] {subprocess.py:93} INFO - üèÉ View run train_v20250817_175136 at: http://mlflow:5000/#/experiments/2/runs/17deb02ded5a4a7eb1d045ec53da69d2
[2025-08-17T17:53:07.526+0000] {subprocess.py:93} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/2
[2025-08-17T17:53:07.527+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-17T17:53:07.529+0000] {subprocess.py:93} INFO -   File "/opt/***/ml_pipeline/models/train_fraud_detector_task.py", line 228, in <module>
[2025-08-17T17:53:07.531+0000] {subprocess.py:93} INFO -     main()
[2025-08-17T17:53:07.533+0000] {subprocess.py:93} INFO -   File "/opt/***/ml_pipeline/models/train_fraud_detector_task.py", line 212, in main
[2025-08-17T17:53:07.535+0000] {subprocess.py:93} INFO -     registered_model = mlflow.register_model(model_uri=model_uri, name=MODEL_NAME)
[2025-08-17T17:53:07.536+0000] {subprocess.py:93} INFO -                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-17T17:53:07.537+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/tracking/_model_registry/fluent.py", line 129, in register_model
[2025-08-17T17:53:07.538+0000] {subprocess.py:93} INFO -     return _register_model(
[2025-08-17T17:53:07.539+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^
[2025-08-17T17:53:07.540+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/tracking/_model_registry/fluent.py", line 180, in _register_model
[2025-08-17T17:53:07.541+0000] {subprocess.py:93} INFO -     raise MlflowException(
[2025-08-17T17:53:07.542+0000] {subprocess.py:93} INFO - mlflow.exceptions.MlflowException: Unable to find a logged_model with artifact_path model under run 17deb02ded5a4a7eb1d045ec53da69d2
[2025-08-17T17:53:08.760+0000] {subprocess.py:93} INFO - ERROR: failed to reproduce 'train_model': failed to run: python models/train_fraud_detector_task.py, exited with 1
[2025-08-17T17:53:18.323+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-08-17T17:53:19.156+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-17T17:53:19.159+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-17T17:53:19.217+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ml_pipeline_dvc, task_id=train_fraud_detector_dvc, run_id=manual__2025-08-17T17:51:27.498563+00:00, execution_date=20250817T175127, start_date=20250817T175244, end_date=20250817T175319
[2025-08-17T17:53:19.272+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-17T17:53:19.301+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-17T17:53:19.303+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
