[2025-08-11T18:33:45.639+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-11T18:33:45.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.init_params manual__2025-08-11T18:33:37.192923+00:00 [queued]>
[2025-08-11T18:33:45.705+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.init_params manual__2025-08-11T18:33:37.192923+00:00 [queued]>
[2025-08-11T18:33:45.706+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-11T18:33:45.730+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): init_params> on 2025-08-11 18:33:37.192923+00:00
[2025-08-11T18:33:45.743+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2317) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-11T18:33:45.746+0000] {standard_task_runner.py:63} INFO - Started process 2322 to run task
[2025-08-11T18:33:45.745+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'init_params', 'manual__2025-08-11T18:33:37.192923+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpt3k9aji9']
[2025-08-11T18:33:45.749+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask init_params
[2025-08-11T18:33:45.844+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.init_params manual__2025-08-11T18:33:37.192923+00:00 [running]> on host 631cb2647807
[2025-08-11T18:33:46.018+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='init_params' AIRFLOW_CTX_EXECUTION_DATE='2025-08-11T18:33:37.192923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-11T18:33:37.192923+00:00'
[2025-08-11T18:33:46.020+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-11T18:33:46.049+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-11T18:33:46.050+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_params_yaml() missing 1 required positional argument: 'version'
[2025-08-11T18:33:46.071+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl, task_id=init_params, run_id=manual__2025-08-11T18:33:37.192923+00:00, execution_date=20250811T183337, start_date=20250811T183345, end_date=20250811T183346
[2025-08-11T18:33:46.097+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 44 for task init_params (create_params_yaml() missing 1 required positional argument: 'version'; 2322)
[2025-08-11T18:33:46.132+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-11T18:33:46.166+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-11T18:33:46.169+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
